FROM asterope/base:latest

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev \
    python3-setuptools \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir poetry virtualenv ipython black pylint

# Make python3 the default python
RUN ln -sf /usr/bin/python3 /usr/local/bin/python

USER coder
